### ISSUE TITLE
Create a quickstarter

### ISSUE THREAD

**Issue by KevinTss** [HackYourFutureBelgium/improvements#2]
We ask them to create a directory structure, but a good way could be a repository that they can fork and work directly on it

Like a super repo `hyf-quickstarter` with all the architecture that they need to work inside, then they won't need to care about how to organise the file and exercices

**Comment by colevandersWands** [comment]
this is much better than just building it in class together.  you can still cover it in class, but don't need to spend all the time building it.

how about calling it this? https://github.com/HackYourFutureBelgium/hacking-my-future

**Comment by KevinTss** [comment]
I guess that `quickstarter` is a good name enough. Also because is common to say `Quick start` on lot of documentation

**Comment by colevandersWands** [comment]
This is now a homework assignment in the 0th module: https://github.com/HackYourFutureBelgium/working-with-code/blob/master/week-1-homework.md#hyf-directory

Decided to describe the directory structure and have them create it directly on their computers instead of as a cloneable repo. The thought being a pre-made repo could be confusing at this point.  they might wonder “am I supposed to push it? commit it?”. or "Why am I cloning other homework projects into this repo?"
